### ISSUE TITLE
Weapon DPS values

### ISSUE THREAD

**Issue by Dromo** [LotroCompanion/lotro-tools#5]
https://github.com/LotroCompanion/lotro-tools/blob/fddadaa307cf3b4fa6777ac4f6e2ca41a5f9d7f5/src/main/java/delta/games/lotro/tools/dat/items/MainDatItemsLoader.java#L563

is there a reason why the damage numbers for max and min damage are typecasted to (int) instead of using Math.round() function?
i have noticed long time ago that the min/max numbers are slightly off, digging a bit more into it now i saw they are just converted to int from float, meaning values like 24.6 becomes 24 instead of 25.

I looked at first 6 weapons from item.xml file, and they all have their damage numbers off compared to tooltips.
since the dps in the .xml file is in float, i used 1.25 and 0.75 modifiers to calculate max and min damage. After rounding these numbers i got the same numbers as shown on tooltips.

**Comment by dmorcellet** [comment]
OK. Thanks for this study and feedback.
DPS is not a priority since it has no impact on stats computations. And may be this one is just a display issue. It may be that they use floats for computations.

**Comment by dmorcellet** [comment]
Done.
